# Generated by Django 5.2.14 on 2026-05-30 05:35

from django.db import migrations

def update_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=1,
        defaults={
            'domain': 'youlyzer.com',
            'name': 'youlyzer.com',
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(update_site, reverse_code=migrations.RunPython.noop),
    ]
