# Generated by Django 5.2.14 on 2026-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="Sender's IP address", null=True),
        ),
    ]
